### PR TITLE
Big Update Reduced Cpu Usage %25 to %15

### PR DESCRIPTION
**Pull request by hasanalt**
There İs Many Code Optimization

### CODE REVIEW

**Comment by martinmiglio** [comment]
I am unsure of the goal of this PR, can you clarify the changes you made?

**Comment by hasanalt** [comment]
its make some changes to reduce image detection cpu usage and rewrote image logging.py because instead of iterating over the files in clear_image_log and then counting them again in count_files_in_directory, you can combine the logic rewrote card_detection.py Dictionary for get_play_coords(): Instead of using multiple lists for different card groups in the get_play_coords() function, a dictionary named coords was introduced. This dictionary stores the coordinates for each card group and side. It simplifies the code and eliminates redundancy.

**Comment by martinmiglio** [comment]
1. Can you update this PR to not change the comments left in the code?
2. `image_logging.py` is code used for development purposes and not in production so its performance is not a concern.
3. If the changes to `image_rec.py` are not intended, please remove them.
4. I do not see how these changes will improve performance.

**Review by martinmiglio — CHANGES_REQUESTED** [review]
1. Can you update this PR to not change the comments left in the code?
2. `image_logging.py` is code used for development purposes and not in production so its performance is not a concern.
3. If the changes to `image_rec.py` are not intended, please remove them.
4. I do not see how these changes will improve performance.

**Comment by hasanalt** [comment]
> 1. Can you update this PR to not change the comments left in the code?
> 2. `image_logging.py` is code used for development purposes and not in production so its performance is not a concern.
> 3. If the changes to `image_rec.py` are not intended, please remove them.
> 4. I do not see how these changes will improve performance.

I actually did this update before, I just didn't upload it to github, I'll update it soon and share it again

**Pull request closed without merging**
